### ISSUE TITLE
[Roadmap] 1.4.2 -> 2.0.0

### ISSUE THREAD

**Issue by auguwu** [NinoDiscord/Nino#772]
## Roadmap
- [ ] **Add slash command variants**
- [x] ~~**Add automod to threads**~~ - You get added to threads if you're not apart of it with the MESSAGE_CREATE gateway event, so not needed
- [ ] **Refractor database models**
- [ ] **Implement [MikaBot/cluster-operator](https://github.com/MikaBot/cluster-operator)**
- [ ] #789
- [ ] #704
- [ ] **Add message highlighting when discord.com/channels/.../messages/... appears**
- [ ] **Rework argument system to be very safe for development and the end user**
- [ ] #275
- [ ] **Add thread commands into moderation (i.e, `no-threads` and `threads`)**
- [ ] **Add tags into Nino with some new features.**
   - [ ] **Scriping Language for complex tags**
   - [ ] **Minimal API for less complex tags**
   - [ ] **Tag Recovery and Export/Import**

**Comment by IceeMC** [comment]
cry fluff
